[mgr]
ratio=[2,4,3]

[preview]
image_quality=90

[opener]
edit = [
    { run = "wt -w 0 nt nvim %s", block = false, for = "windows", desc = "Nvim"},
    { run = "code %s", block = false, for = "windows", desc = "Code" },
    { run = "wt -w 0 new-tab -d %d1", block = false, for = "windows", desc = "Terminal - Tab" },
    { run = "wt -w 0 split-pane -d %d1", block = false, for = "windows", desc = "Terminal - Pane Vertical" },
    { run = "wt -w 0 split-pane -H -d %d1", block = false, for = "windows", desc = "Terminal - Pane Horizontal" },
]

firefox = [
{ run = '"C:\Program Files\Mozilla Firefox\firefox.exe" -url %S1', block = false, desc = "FireFox", for = "windows" },
]

[open]
prepend_rules = [
    { url = "*.md", use = ["firefox", "edit"]}
]
